// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file taptime/services/admin.proto (package com.whs31.taptime.services, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";
import { User } from "../user_pb.js";
import { Uuid } from "../uuid_pb.js";

/**
 * @generated from enum com.whs31.taptime.services.BanKind
 */
export enum BanKind {
  /**
   * @generated from enum value: BAN_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: BAN_KIND_USER = 1;
   */
  USER = 1,

  /**
   * @generated from enum value: BAN_KIND_IP = 2;
   */
  IP = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(BanKind)
proto3.util.setEnumType(BanKind, "com.whs31.taptime.services.BanKind", [
  { no: 0, name: "BAN_KIND_UNSPECIFIED" },
  { no: 1, name: "BAN_KIND_USER" },
  { no: 2, name: "BAN_KIND_IP" },
]);

/**
 * @generated from message com.whs31.taptime.services.AdminLoginRequest
 */
export class AdminLoginRequest extends Message<AdminLoginRequest> {
  /**
   * @generated from field: string password = 1;
   */
  password = "";

  constructor(data?: PartialMessage<AdminLoginRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.AdminLoginRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminLoginRequest {
    return new AdminLoginRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminLoginRequest {
    return new AdminLoginRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminLoginRequest {
    return new AdminLoginRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AdminLoginRequest | PlainMessage<AdminLoginRequest> | undefined, b: AdminLoginRequest | PlainMessage<AdminLoginRequest> | undefined): boolean {
    return proto3.util.equals(AdminLoginRequest, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.services.AdminLoginResponse
 */
export class AdminLoginResponse extends Message<AdminLoginResponse> {
  /**
   * @generated from field: string admin_token = 1;
   */
  adminToken = "";

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 2;
   */
  expiresAt?: Timestamp;

  constructor(data?: PartialMessage<AdminLoginResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.AdminLoginResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "admin_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "expires_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminLoginResponse {
    return new AdminLoginResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminLoginResponse {
    return new AdminLoginResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminLoginResponse {
    return new AdminLoginResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AdminLoginResponse | PlainMessage<AdminLoginResponse> | undefined, b: AdminLoginResponse | PlainMessage<AdminLoginResponse> | undefined): boolean {
    return proto3.util.equals(AdminLoginResponse, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.services.ListUsersRequest
 */
export class ListUsersRequest extends Message<ListUsersRequest> {
  /**
   * @generated from field: string query = 1;
   */
  query = "";

  /**
   * @generated from field: int32 limit = 2;
   */
  limit = 0;

  /**
   * @generated from field: int32 offset = 3;
   */
  offset = 0;

  constructor(data?: PartialMessage<ListUsersRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.ListUsersRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "query", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "offset", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListUsersRequest {
    return new ListUsersRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListUsersRequest {
    return new ListUsersRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListUsersRequest {
    return new ListUsersRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListUsersRequest | PlainMessage<ListUsersRequest> | undefined, b: ListUsersRequest | PlainMessage<ListUsersRequest> | undefined): boolean {
    return proto3.util.equals(ListUsersRequest, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.services.AdminUserListItem
 */
export class AdminUserListItem extends Message<AdminUserListItem> {
  /**
   * @generated from field: com.whs31.taptime.User user = 1;
   */
  user?: User;

  /**
   * @generated from field: bool user_banned = 2;
   */
  userBanned = false;

  /**
   * @generated from field: int64 known_ip_count = 3;
   */
  knownIpCount = protoInt64.zero;

  constructor(data?: PartialMessage<AdminUserListItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.AdminUserListItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user", kind: "message", T: User },
    { no: 2, name: "user_banned", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "known_ip_count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminUserListItem {
    return new AdminUserListItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminUserListItem {
    return new AdminUserListItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminUserListItem {
    return new AdminUserListItem().fromJsonString(jsonString, options);
  }

  static equals(a: AdminUserListItem | PlainMessage<AdminUserListItem> | undefined, b: AdminUserListItem | PlainMessage<AdminUserListItem> | undefined): boolean {
    return proto3.util.equals(AdminUserListItem, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.services.ListUsersResponse
 */
export class ListUsersResponse extends Message<ListUsersResponse> {
  /**
   * @generated from field: repeated com.whs31.taptime.services.AdminUserListItem users = 1;
   */
  users: AdminUserListItem[] = [];

  /**
   * @generated from field: int64 total = 2;
   */
  total = protoInt64.zero;

  constructor(data?: PartialMessage<ListUsersResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.ListUsersResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "users", kind: "message", T: AdminUserListItem, repeated: true },
    { no: 2, name: "total", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListUsersResponse {
    return new ListUsersResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListUsersResponse {
    return new ListUsersResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListUsersResponse {
    return new ListUsersResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListUsersResponse | PlainMessage<ListUsersResponse> | undefined, b: ListUsersResponse | PlainMessage<ListUsersResponse> | undefined): boolean {
    return proto3.util.equals(ListUsersResponse, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.services.GetUserDetailRequest
 */
export class GetUserDetailRequest extends Message<GetUserDetailRequest> {
  /**
   * @generated from field: com.whs31.taptime.Uuid user_id = 1;
   */
  userId?: Uuid;

  constructor(data?: PartialMessage<GetUserDetailRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.GetUserDetailRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "message", T: Uuid },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetUserDetailRequest {
    return new GetUserDetailRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetUserDetailRequest {
    return new GetUserDetailRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetUserDetailRequest {
    return new GetUserDetailRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetUserDetailRequest | PlainMessage<GetUserDetailRequest> | undefined, b: GetUserDetailRequest | PlainMessage<GetUserDetailRequest> | undefined): boolean {
    return proto3.util.equals(GetUserDetailRequest, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.services.AdminUserDetail
 */
export class AdminUserDetail extends Message<AdminUserDetail> {
  /**
   * @generated from field: com.whs31.taptime.User user = 1;
   */
  user?: User;

  /**
   * @generated from field: repeated com.whs31.taptime.services.KnownIpAddress known_ips = 2;
   */
  knownIps: KnownIpAddress[] = [];

  /**
   * @generated from field: repeated com.whs31.taptime.services.BanRecord bans = 3;
   */
  bans: BanRecord[] = [];

  /**
   * @generated from field: int64 event_count = 4;
   */
  eventCount = protoInt64.zero;

  /**
   * @generated from field: int64 day_flag_count = 5;
   */
  dayFlagCount = protoInt64.zero;

  constructor(data?: PartialMessage<AdminUserDetail>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.AdminUserDetail";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user", kind: "message", T: User },
    { no: 2, name: "known_ips", kind: "message", T: KnownIpAddress, repeated: true },
    { no: 3, name: "bans", kind: "message", T: BanRecord, repeated: true },
    { no: 4, name: "event_count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "day_flag_count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminUserDetail {
    return new AdminUserDetail().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminUserDetail {
    return new AdminUserDetail().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminUserDetail {
    return new AdminUserDetail().fromJsonString(jsonString, options);
  }

  static equals(a: AdminUserDetail | PlainMessage<AdminUserDetail> | undefined, b: AdminUserDetail | PlainMessage<AdminUserDetail> | undefined): boolean {
    return proto3.util.equals(AdminUserDetail, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.services.KnownIpAddress
 */
export class KnownIpAddress extends Message<KnownIpAddress> {
  /**
   * @generated from field: string ip = 1;
   */
  ip = "";

  /**
   * @generated from field: google.protobuf.Timestamp first_seen = 2;
   */
  firstSeen?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp last_seen = 3;
   */
  lastSeen?: Timestamp;

  /**
   * @generated from field: int64 request_count = 4;
   */
  requestCount = protoInt64.zero;

  constructor(data?: PartialMessage<KnownIpAddress>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.KnownIpAddress";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ip", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "first_seen", kind: "message", T: Timestamp },
    { no: 3, name: "last_seen", kind: "message", T: Timestamp },
    { no: 4, name: "request_count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): KnownIpAddress {
    return new KnownIpAddress().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): KnownIpAddress {
    return new KnownIpAddress().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): KnownIpAddress {
    return new KnownIpAddress().fromJsonString(jsonString, options);
  }

  static equals(a: KnownIpAddress | PlainMessage<KnownIpAddress> | undefined, b: KnownIpAddress | PlainMessage<KnownIpAddress> | undefined): boolean {
    return proto3.util.equals(KnownIpAddress, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.services.BanRecord
 */
export class BanRecord extends Message<BanRecord> {
  /**
   * @generated from field: com.whs31.taptime.Uuid id = 1;
   */
  id?: Uuid;

  /**
   * @generated from field: com.whs31.taptime.services.BanKind kind = 2;
   */
  kind = BanKind.UNSPECIFIED;

  /**
   * @generated from field: optional com.whs31.taptime.Uuid user_id = 3;
   */
  userId?: Uuid;

  /**
   * @generated from field: string ip_cidr = 4;
   */
  ipCidr = "";

  /**
   * @generated from field: string reason = 5;
   */
  reason = "";

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp expires_at = 7;
   */
  expiresAt?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp revoked_at = 8;
   */
  revokedAt?: Timestamp;

  /**
   * @generated from field: bool active = 9;
   */
  active = false;

  constructor(data?: PartialMessage<BanRecord>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.BanRecord";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: Uuid },
    { no: 2, name: "kind", kind: "enum", T: proto3.getEnumType(BanKind) },
    { no: 3, name: "user_id", kind: "message", T: Uuid, opt: true },
    { no: 4, name: "ip_cidr", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "created_at", kind: "message", T: Timestamp },
    { no: 7, name: "expires_at", kind: "message", T: Timestamp, opt: true },
    { no: 8, name: "revoked_at", kind: "message", T: Timestamp, opt: true },
    { no: 9, name: "active", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BanRecord {
    return new BanRecord().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BanRecord {
    return new BanRecord().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BanRecord {
    return new BanRecord().fromJsonString(jsonString, options);
  }

  static equals(a: BanRecord | PlainMessage<BanRecord> | undefined, b: BanRecord | PlainMessage<BanRecord> | undefined): boolean {
    return proto3.util.equals(BanRecord, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.services.ListBansRequest
 */
export class ListBansRequest extends Message<ListBansRequest> {
  /**
   * @generated from field: com.whs31.taptime.services.BanKind kind = 1;
   */
  kind = BanKind.UNSPECIFIED;

  /**
   * @generated from field: bool include_inactive = 2;
   */
  includeInactive = false;

  constructor(data?: PartialMessage<ListBansRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.ListBansRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "kind", kind: "enum", T: proto3.getEnumType(BanKind) },
    { no: 2, name: "include_inactive", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListBansRequest {
    return new ListBansRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListBansRequest {
    return new ListBansRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListBansRequest {
    return new ListBansRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListBansRequest | PlainMessage<ListBansRequest> | undefined, b: ListBansRequest | PlainMessage<ListBansRequest> | undefined): boolean {
    return proto3.util.equals(ListBansRequest, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.services.ListBansResponse
 */
export class ListBansResponse extends Message<ListBansResponse> {
  /**
   * @generated from field: repeated com.whs31.taptime.services.BanRecord bans = 1;
   */
  bans: BanRecord[] = [];

  constructor(data?: PartialMessage<ListBansResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.ListBansResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "bans", kind: "message", T: BanRecord, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListBansResponse {
    return new ListBansResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListBansResponse {
    return new ListBansResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListBansResponse {
    return new ListBansResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListBansResponse | PlainMessage<ListBansResponse> | undefined, b: ListBansResponse | PlainMessage<ListBansResponse> | undefined): boolean {
    return proto3.util.equals(ListBansResponse, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.services.CreateBanRequest
 */
export class CreateBanRequest extends Message<CreateBanRequest> {
  /**
   * @generated from field: com.whs31.taptime.services.BanKind kind = 1;
   */
  kind = BanKind.UNSPECIFIED;

  /**
   * @generated from field: optional com.whs31.taptime.Uuid user_id = 2;
   */
  userId?: Uuid;

  /**
   * @generated from field: string ip_cidr = 3;
   */
  ipCidr = "";

  /**
   * @generated from field: string reason = 4;
   */
  reason = "";

  /**
   * @generated from field: optional google.protobuf.Timestamp expires_at = 5;
   */
  expiresAt?: Timestamp;

  constructor(data?: PartialMessage<CreateBanRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.CreateBanRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "kind", kind: "enum", T: proto3.getEnumType(BanKind) },
    { no: 2, name: "user_id", kind: "message", T: Uuid, opt: true },
    { no: 3, name: "ip_cidr", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "expires_at", kind: "message", T: Timestamp, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateBanRequest {
    return new CreateBanRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateBanRequest {
    return new CreateBanRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateBanRequest {
    return new CreateBanRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateBanRequest | PlainMessage<CreateBanRequest> | undefined, b: CreateBanRequest | PlainMessage<CreateBanRequest> | undefined): boolean {
    return proto3.util.equals(CreateBanRequest, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.services.RevokeBanRequest
 */
export class RevokeBanRequest extends Message<RevokeBanRequest> {
  /**
   * @generated from field: com.whs31.taptime.Uuid ban_id = 1;
   */
  banId?: Uuid;

  /**
   * @generated from field: com.whs31.taptime.services.BanKind kind = 2;
   */
  kind = BanKind.UNSPECIFIED;

  constructor(data?: PartialMessage<RevokeBanRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.RevokeBanRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ban_id", kind: "message", T: Uuid },
    { no: 2, name: "kind", kind: "enum", T: proto3.getEnumType(BanKind) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RevokeBanRequest {
    return new RevokeBanRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RevokeBanRequest {
    return new RevokeBanRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RevokeBanRequest {
    return new RevokeBanRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RevokeBanRequest | PlainMessage<RevokeBanRequest> | undefined, b: RevokeBanRequest | PlainMessage<RevokeBanRequest> | undefined): boolean {
    return proto3.util.equals(RevokeBanRequest, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.services.DeleteUserRequest
 */
export class DeleteUserRequest extends Message<DeleteUserRequest> {
  /**
   * @generated from field: com.whs31.taptime.Uuid user_id = 1;
   */
  userId?: Uuid;

  constructor(data?: PartialMessage<DeleteUserRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.DeleteUserRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "message", T: Uuid },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteUserRequest {
    return new DeleteUserRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteUserRequest {
    return new DeleteUserRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteUserRequest {
    return new DeleteUserRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteUserRequest | PlainMessage<DeleteUserRequest> | undefined, b: DeleteUserRequest | PlainMessage<DeleteUserRequest> | undefined): boolean {
    return proto3.util.equals(DeleteUserRequest, a, b);
  }
}

