// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file taptime/services/admin.proto (package com.whs31.taptime.services, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AdminLoginRequest, AdminLoginResponse, AdminUserDetail, BanRecord, CreateBanRequest, DeleteUserRequest, GetUserDetailRequest, ListBansRequest, ListBansResponse, ListUsersRequest, ListUsersResponse, RevokeBanRequest } from "./admin_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service com.whs31.taptime.services.AdminService
 */
export const AdminService = {
  typeName: "com.whs31.taptime.services.AdminService",
  methods: {
    /**
     * @generated from rpc com.whs31.taptime.services.AdminService.AdminLogin
     */
    adminLogin: {
      name: "AdminLogin",
      I: AdminLoginRequest,
      O: AdminLoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.whs31.taptime.services.AdminService.ListUsers
     */
    listUsers: {
      name: "ListUsers",
      I: ListUsersRequest,
      O: ListUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.whs31.taptime.services.AdminService.GetUserDetail
     */
    getUserDetail: {
      name: "GetUserDetail",
      I: GetUserDetailRequest,
      O: AdminUserDetail,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.whs31.taptime.services.AdminService.ListBans
     */
    listBans: {
      name: "ListBans",
      I: ListBansRequest,
      O: ListBansResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.whs31.taptime.services.AdminService.CreateBan
     */
    createBan: {
      name: "CreateBan",
      I: CreateBanRequest,
      O: BanRecord,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.whs31.taptime.services.AdminService.RevokeBan
     */
    revokeBan: {
      name: "RevokeBan",
      I: RevokeBanRequest,
      O: BanRecord,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.whs31.taptime.services.AdminService.DeleteUserTimeData
     */
    deleteUserTimeData: {
      name: "DeleteUserTimeData",
      I: DeleteUserRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.whs31.taptime.services.AdminService.DeleteUserAccount
     */
    deleteUserAccount: {
      name: "DeleteUserAccount",
      I: DeleteUserRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

