// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file taptime/services/auth.proto (package com.whs31.taptime.services, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AuthResponse, LoginRequest, RegisterUserRequest } from "./auth_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";
import { User } from "../user_pb.js";

/**
 * @generated from service com.whs31.taptime.services.AuthService
 */
export const AuthService = {
  typeName: "com.whs31.taptime.services.AuthService",
  methods: {
    /**
     * @generated from rpc com.whs31.taptime.services.AuthService.RegisterUser
     */
    registerUser: {
      name: "RegisterUser",
      I: RegisterUserRequest,
      O: AuthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.whs31.taptime.services.AuthService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: AuthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.whs31.taptime.services.AuthService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: Empty,
      O: User,
      kind: MethodKind.Unary,
    },
  }
} as const;

