// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file taptime/services/auth.proto (package com.whs31.taptime.services, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AuthResponse, DeleteAccountRequest, LoginRequest, RegisterUserRequest, UpdateProfileRequest, UpdateRfidUidRequest, UpdateSettingsRequest } from "./auth_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";
import { User } from "../user_pb.js";

/**
 * @generated from service com.whs31.taptime.services.AuthService
 */
export const AuthService = {
  typeName: "com.whs31.taptime.services.AuthService",
  methods: {
    /**
     * @generated from rpc com.whs31.taptime.services.AuthService.RegisterUser
     */
    registerUser: {
      name: "RegisterUser",
      I: RegisterUserRequest,
      O: AuthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.whs31.taptime.services.AuthService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: AuthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.whs31.taptime.services.AuthService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: Empty,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.whs31.taptime.services.AuthService.UpdateProfile
     */
    updateProfile: {
      name: "UpdateProfile",
      I: UpdateProfileRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.whs31.taptime.services.AuthService.UpdateSettings
     */
    updateSettings: {
      name: "UpdateSettings",
      I: UpdateSettingsRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.whs31.taptime.services.AuthService.UpdateRfidUid
     */
    updateRfidUid: {
      name: "UpdateRfidUid",
      I: UpdateRfidUidRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.whs31.taptime.services.AuthService.DeleteTimeData
     */
    deleteTimeData: {
      name: "DeleteTimeData",
      I: Empty,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.whs31.taptime.services.AuthService.DeleteAccount
     */
    deleteAccount: {
      name: "DeleteAccount",
      I: DeleteAccountRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

