// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file taptime/services/store.proto (package com.whs31.taptime.services, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Date } from "../date_pb.js";
import { Day } from "../day_pb.js";
import { Duration, Empty, MethodKind } from "@bufbuild/protobuf";
import { Balance } from "../balance_pb.js";
import { EventRequest, SetFlagRequest } from "./store_pb.js";

/**
 * @generated from service com.whs31.taptime.services.StoreService
 */
export const StoreService = {
  typeName: "com.whs31.taptime.services.StoreService",
  methods: {
    /**
     * @generated from rpc com.whs31.taptime.services.StoreService.GetDay
     */
    getDay: {
      name: "GetDay",
      I: Date,
      O: Day,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.whs31.taptime.services.StoreService.GetWorkHours
     */
    getWorkHours: {
      name: "GetWorkHours",
      I: Date,
      O: Duration,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.whs31.taptime.services.StoreService.GetBalance
     */
    getBalance: {
      name: "GetBalance",
      I: Date,
      O: Balance,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.whs31.taptime.services.StoreService.SetFlag
     */
    setFlag: {
      name: "SetFlag",
      I: SetFlagRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.whs31.taptime.services.StoreService.AddCheckIn
     */
    addCheckIn: {
      name: "AddCheckIn",
      I: EventRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.whs31.taptime.services.StoreService.AddCheckOut
     */
    addCheckOut: {
      name: "AddCheckOut",
      I: EventRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

