// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file taptime/services/store.proto (package com.whs31.taptime.services, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Date } from "../date_pb.js";
import { DayFlag } from "../day_pb.js";
import { LocalTime } from "../local_time_pb.js";

/**
 * @generated from message com.whs31.taptime.services.SetFlagRequest
 */
export class SetFlagRequest extends Message<SetFlagRequest> {
  /**
   * @generated from field: com.whs31.taptime.Date date = 1;
   */
  date?: Date;

  /**
   * @generated from field: com.whs31.taptime.DayFlag flag = 2;
   */
  flag = DayFlag.NONE;

  constructor(data?: PartialMessage<SetFlagRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.SetFlagRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "date", kind: "message", T: Date },
    { no: 2, name: "flag", kind: "enum", T: proto3.getEnumType(DayFlag) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetFlagRequest {
    return new SetFlagRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetFlagRequest {
    return new SetFlagRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetFlagRequest {
    return new SetFlagRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SetFlagRequest | PlainMessage<SetFlagRequest> | undefined, b: SetFlagRequest | PlainMessage<SetFlagRequest> | undefined): boolean {
    return proto3.util.equals(SetFlagRequest, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.services.EventRequest
 */
export class EventRequest extends Message<EventRequest> {
  /**
   * @generated from field: com.whs31.taptime.Date date = 1;
   */
  date?: Date;

  /**
   * @generated from field: com.whs31.taptime.LocalTime time = 2;
   */
  time?: LocalTime;

  constructor(data?: PartialMessage<EventRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.EventRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "date", kind: "message", T: Date },
    { no: 2, name: "time", kind: "message", T: LocalTime },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventRequest {
    return new EventRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventRequest {
    return new EventRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventRequest {
    return new EventRequest().fromJsonString(jsonString, options);
  }

  static equals(a: EventRequest | PlainMessage<EventRequest> | undefined, b: EventRequest | PlainMessage<EventRequest> | undefined): boolean {
    return proto3.util.equals(EventRequest, a, b);
  }
}

