// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file taptime/services/store.proto (package com.whs31.taptime.services, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Duration, Message, proto3 } from "@bufbuild/protobuf";
import { Date } from "../date_pb.js";
import { Day, DayFlag } from "../day_pb.js";
import { Balance } from "../balance_pb.js";
import { LocalTime } from "../local_time_pb.js";
import { Uuid } from "../uuid_pb.js";

/**
 * @generated from message com.whs31.taptime.services.DashboardRequest
 */
export class DashboardRequest extends Message<DashboardRequest> {
  /**
   * @generated from field: com.whs31.taptime.Date range_start = 1;
   */
  rangeStart?: Date;

  /**
   * @generated from field: com.whs31.taptime.Date range_end = 2;
   */
  rangeEnd?: Date;

  /**
   * @generated from field: com.whs31.taptime.Date month_start = 3;
   */
  monthStart?: Date;

  /**
   * @generated from field: com.whs31.taptime.Date month_end = 4;
   */
  monthEnd?: Date;

  /**
   * @generated from field: com.whs31.taptime.Date today = 5;
   */
  today?: Date;

  constructor(data?: PartialMessage<DashboardRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.DashboardRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "range_start", kind: "message", T: Date },
    { no: 2, name: "range_end", kind: "message", T: Date },
    { no: 3, name: "month_start", kind: "message", T: Date },
    { no: 4, name: "month_end", kind: "message", T: Date },
    { no: 5, name: "today", kind: "message", T: Date },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DashboardRequest {
    return new DashboardRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DashboardRequest {
    return new DashboardRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DashboardRequest {
    return new DashboardRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DashboardRequest | PlainMessage<DashboardRequest> | undefined, b: DashboardRequest | PlainMessage<DashboardRequest> | undefined): boolean {
    return proto3.util.equals(DashboardRequest, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.services.DashboardResponse
 */
export class DashboardResponse extends Message<DashboardResponse> {
  /**
   * @generated from field: repeated com.whs31.taptime.services.DaySummary days = 1;
   */
  days: DaySummary[] = [];

  /**
   * @generated from field: com.whs31.taptime.services.MonthlyStats month_stats = 2;
   */
  monthStats?: MonthlyStats;

  constructor(data?: PartialMessage<DashboardResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.DashboardResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "days", kind: "message", T: DaySummary, repeated: true },
    { no: 2, name: "month_stats", kind: "message", T: MonthlyStats },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DashboardResponse {
    return new DashboardResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DashboardResponse {
    return new DashboardResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DashboardResponse {
    return new DashboardResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DashboardResponse | PlainMessage<DashboardResponse> | undefined, b: DashboardResponse | PlainMessage<DashboardResponse> | undefined): boolean {
    return proto3.util.equals(DashboardResponse, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.services.DaySummary
 */
export class DaySummary extends Message<DaySummary> {
  /**
   * @generated from field: com.whs31.taptime.Day day = 1;
   */
  day?: Day;

  /**
   * @generated from field: google.protobuf.Duration clocked_work = 2;
   */
  clockedWork?: Duration;

  /**
   * @generated from field: com.whs31.taptime.Balance balance = 3;
   */
  balance?: Balance;

  /**
   * @generated from field: bool skipped = 4;
   */
  skipped = false;

  /**
   * @generated from field: bool full_day_worked = 5;
   */
  fullDayWorked = false;

  /**
   * @generated from field: bool required_work_hours_overridden = 6;
   */
  requiredWorkHoursOverridden = false;

  /**
   * @generated from field: google.protobuf.Duration work_target = 7;
   */
  workTarget?: Duration;

  /**
   * @generated from field: bool before_start_date = 8;
   */
  beforeStartDate = false;

  constructor(data?: PartialMessage<DaySummary>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.DaySummary";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "day", kind: "message", T: Day },
    { no: 2, name: "clocked_work", kind: "message", T: Duration },
    { no: 3, name: "balance", kind: "message", T: Balance },
    { no: 4, name: "skipped", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "full_day_worked", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "required_work_hours_overridden", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 7, name: "work_target", kind: "message", T: Duration },
    { no: 8, name: "before_start_date", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DaySummary {
    return new DaySummary().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DaySummary {
    return new DaySummary().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DaySummary {
    return new DaySummary().fromJsonString(jsonString, options);
  }

  static equals(a: DaySummary | PlainMessage<DaySummary> | undefined, b: DaySummary | PlainMessage<DaySummary> | undefined): boolean {
    return proto3.util.equals(DaySummary, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.services.MonthlyStats
 */
export class MonthlyStats extends Message<MonthlyStats> {
  /**
   * @generated from field: google.protobuf.Duration total_clocked_work = 1;
   */
  totalClockedWork?: Duration;

  /**
   * @generated from field: google.protobuf.Duration overtime = 2;
   */
  overtime?: Duration;

  /**
   * @generated from field: google.protobuf.Duration undertime = 3;
   */
  undertime?: Duration;

  /**
   * @generated from field: uint32 worked_days = 4;
   */
  workedDays = 0;

  /**
   * @generated from field: uint32 remote_days = 5;
   */
  remoteDays = 0;

  /**
   * @generated from field: uint32 day_offs = 6;
   */
  dayOffs = 0;

  /**
   * @generated from field: uint32 vacation_days = 7;
   */
  vacationDays = 0;

  /**
   * @generated from field: uint32 skipped_days = 8;
   */
  skippedDays = 0;

  /**
   * @generated from field: uint32 full_weekend_work_days = 9;
   */
  fullWeekendWorkDays = 0;

  /**
   * @generated from field: uint32 full_vacation_work_days = 10;
   */
  fullVacationWorkDays = 0;

  constructor(data?: PartialMessage<MonthlyStats>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.MonthlyStats";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "total_clocked_work", kind: "message", T: Duration },
    { no: 2, name: "overtime", kind: "message", T: Duration },
    { no: 3, name: "undertime", kind: "message", T: Duration },
    { no: 4, name: "worked_days", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 5, name: "remote_days", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 6, name: "day_offs", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 7, name: "vacation_days", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 8, name: "skipped_days", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 9, name: "full_weekend_work_days", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 10, name: "full_vacation_work_days", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MonthlyStats {
    return new MonthlyStats().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MonthlyStats {
    return new MonthlyStats().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MonthlyStats {
    return new MonthlyStats().fromJsonString(jsonString, options);
  }

  static equals(a: MonthlyStats | PlainMessage<MonthlyStats> | undefined, b: MonthlyStats | PlainMessage<MonthlyStats> | undefined): boolean {
    return proto3.util.equals(MonthlyStats, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.services.SetFlagRequest
 */
export class SetFlagRequest extends Message<SetFlagRequest> {
  /**
   * @generated from field: com.whs31.taptime.Date date = 1;
   */
  date?: Date;

  /**
   * @generated from field: com.whs31.taptime.DayFlag flag = 2;
   */
  flag = DayFlag.NONE;

  constructor(data?: PartialMessage<SetFlagRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.SetFlagRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "date", kind: "message", T: Date },
    { no: 2, name: "flag", kind: "enum", T: proto3.getEnumType(DayFlag) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetFlagRequest {
    return new SetFlagRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetFlagRequest {
    return new SetFlagRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetFlagRequest {
    return new SetFlagRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SetFlagRequest | PlainMessage<SetFlagRequest> | undefined, b: SetFlagRequest | PlainMessage<SetFlagRequest> | undefined): boolean {
    return proto3.util.equals(SetFlagRequest, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.services.SetRequiredWorkHoursOverrideRequest
 */
export class SetRequiredWorkHoursOverrideRequest extends Message<SetRequiredWorkHoursOverrideRequest> {
  /**
   * @generated from field: com.whs31.taptime.Date date = 1;
   */
  date?: Date;

  /**
   * @generated from field: google.protobuf.Duration required_work_hours = 2;
   */
  requiredWorkHours?: Duration;

  constructor(data?: PartialMessage<SetRequiredWorkHoursOverrideRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.SetRequiredWorkHoursOverrideRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "date", kind: "message", T: Date },
    { no: 2, name: "required_work_hours", kind: "message", T: Duration },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetRequiredWorkHoursOverrideRequest {
    return new SetRequiredWorkHoursOverrideRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetRequiredWorkHoursOverrideRequest {
    return new SetRequiredWorkHoursOverrideRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetRequiredWorkHoursOverrideRequest {
    return new SetRequiredWorkHoursOverrideRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SetRequiredWorkHoursOverrideRequest | PlainMessage<SetRequiredWorkHoursOverrideRequest> | undefined, b: SetRequiredWorkHoursOverrideRequest | PlainMessage<SetRequiredWorkHoursOverrideRequest> | undefined): boolean {
    return proto3.util.equals(SetRequiredWorkHoursOverrideRequest, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.services.EventRequest
 */
export class EventRequest extends Message<EventRequest> {
  /**
   * @generated from field: com.whs31.taptime.Date date = 1;
   */
  date?: Date;

  /**
   * @generated from field: com.whs31.taptime.LocalTime time = 2;
   */
  time?: LocalTime;

  constructor(data?: PartialMessage<EventRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.EventRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "date", kind: "message", T: Date },
    { no: 2, name: "time", kind: "message", T: LocalTime },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventRequest {
    return new EventRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventRequest {
    return new EventRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventRequest {
    return new EventRequest().fromJsonString(jsonString, options);
  }

  static equals(a: EventRequest | PlainMessage<EventRequest> | undefined, b: EventRequest | PlainMessage<EventRequest> | undefined): boolean {
    return proto3.util.equals(EventRequest, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.services.DeleteEventRequest
 */
export class DeleteEventRequest extends Message<DeleteEventRequest> {
  /**
   * @generated from field: com.whs31.taptime.Uuid event_id = 1;
   */
  eventId?: Uuid;

  constructor(data?: PartialMessage<DeleteEventRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.services.DeleteEventRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event_id", kind: "message", T: Uuid },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteEventRequest {
    return new DeleteEventRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteEventRequest {
    return new DeleteEventRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteEventRequest {
    return new DeleteEventRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteEventRequest | PlainMessage<DeleteEventRequest> | undefined, b: DeleteEventRequest | PlainMessage<DeleteEventRequest> | undefined): boolean {
    return proto3.util.equals(DeleteEventRequest, a, b);
  }
}

