// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file taptime/balance.proto (package com.whs31.taptime, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Duration, Empty, Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message com.whs31.taptime.Balance
 */
export class Balance extends Message<Balance> {
  /**
   * @generated from oneof com.whs31.taptime.Balance.balance_type
   */
  balanceType: {
    /**
     * @generated from field: google.protobuf.Duration overtime = 1;
     */
    value: Duration;
    case: "overtime";
  } | {
    /**
     * @generated from field: google.protobuf.Empty exact = 2;
     */
    value: Empty;
    case: "exact";
  } | {
    /**
     * @generated from field: google.protobuf.Duration under_time = 3;
     */
    value: Duration;
    case: "underTime";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<Balance>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.Balance";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "overtime", kind: "message", T: Duration, oneof: "balance_type" },
    { no: 2, name: "exact", kind: "message", T: Empty, oneof: "balance_type" },
    { no: 3, name: "under_time", kind: "message", T: Duration, oneof: "balance_type" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Balance {
    return new Balance().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Balance {
    return new Balance().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Balance {
    return new Balance().fromJsonString(jsonString, options);
  }

  static equals(a: Balance | PlainMessage<Balance> | undefined, b: Balance | PlainMessage<Balance> | undefined): boolean {
    return proto3.util.equals(Balance, a, b);
  }
}

