// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file taptime/day.proto (package com.whs31.taptime, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Duration, Message, proto3 } from "@bufbuild/protobuf";
import { Date } from "./date_pb.js";
import { Event } from "./event_pb.js";

/**
 * @generated from enum com.whs31.taptime.DayFlag
 */
export enum DayFlag {
  /**
   * @generated from enum value: DAY_FLAG_NONE = 0;
   */
  NONE = 0,

  /**
   * @generated from enum value: DAY_FLAG_WEEKEND = 1;
   */
  WEEKEND = 1,

  /**
   * @generated from enum value: DAY_FLAG_DAY_OFF = 2;
   */
  DAY_OFF = 2,

  /**
   * @generated from enum value: DAY_FLAG_REMOTE = 4;
   */
  REMOTE = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(DayFlag)
proto3.util.setEnumType(DayFlag, "com.whs31.taptime.DayFlag", [
  { no: 0, name: "DAY_FLAG_NONE" },
  { no: 1, name: "DAY_FLAG_WEEKEND" },
  { no: 2, name: "DAY_FLAG_DAY_OFF" },
  { no: 4, name: "DAY_FLAG_REMOTE" },
]);

/**
 * @generated from message com.whs31.taptime.Day
 */
export class Day extends Message<Day> {
  /**
   * @generated from field: com.whs31.taptime.Date date = 1;
   */
  date?: Date;

  /**
   * @generated from field: repeated com.whs31.taptime.Event events = 2;
   */
  events: Event[] = [];

  /**
   * @generated from field: uint32 flags = 3;
   */
  flags = 0;

  /**
   * @generated from field: google.protobuf.Duration required_work_hours = 4;
   */
  requiredWorkHours?: Duration;

  /**
   * @generated from field: google.protobuf.Duration lunch_break_duration = 5;
   */
  lunchBreakDuration?: Duration;

  constructor(data?: PartialMessage<Day>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.Day";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "date", kind: "message", T: Date },
    { no: 2, name: "events", kind: "message", T: Event, repeated: true },
    { no: 3, name: "flags", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "required_work_hours", kind: "message", T: Duration },
    { no: 5, name: "lunch_break_duration", kind: "message", T: Duration },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Day {
    return new Day().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Day {
    return new Day().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Day {
    return new Day().fromJsonString(jsonString, options);
  }

  static equals(a: Day | PlainMessage<Day> | undefined, b: Day | PlainMessage<Day> | undefined): boolean {
    return proto3.util.equals(Day, a, b);
  }
}

