// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file taptime/event.proto (package com.whs31.taptime, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { LocalTime } from "./local_time_pb.js";

/**
 * @generated from message com.whs31.taptime.Event
 */
export class Event extends Message<Event> {
  /**
   * @generated from oneof com.whs31.taptime.Event.event_type
   */
  eventType: {
    /**
     * @generated from field: com.whs31.taptime.LocalTime check_in = 1;
     */
    value: LocalTime;
    case: "checkIn";
  } | {
    /**
     * @generated from field: com.whs31.taptime.LocalTime check_out = 2;
     */
    value: LocalTime;
    case: "checkOut";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<Event>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.Event";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "check_in", kind: "message", T: LocalTime, oneof: "event_type" },
    { no: 2, name: "check_out", kind: "message", T: LocalTime, oneof: "event_type" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Event {
    return new Event().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Event {
    return new Event().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Event {
    return new Event().fromJsonString(jsonString, options);
  }

  static equals(a: Event | PlainMessage<Event> | undefined, b: Event | PlainMessage<Event> | undefined): boolean {
    return proto3.util.equals(Event, a, b);
  }
}

