// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file taptime/local_time.proto (package com.whs31.taptime, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message com.whs31.taptime.LocalTime
 */
export class LocalTime extends Message<LocalTime> {
  /**
   * @generated from field: uint32 hour = 1;
   */
  hour = 0;

  /**
   * @generated from field: uint32 minute = 2;
   */
  minute = 0;

  /**
   * @generated from field: uint32 second = 3;
   */
  second = 0;

  constructor(data?: PartialMessage<LocalTime>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.LocalTime";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "hour", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "minute", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "second", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LocalTime {
    return new LocalTime().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LocalTime {
    return new LocalTime().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LocalTime {
    return new LocalTime().fromJsonString(jsonString, options);
  }

  static equals(a: LocalTime | PlainMessage<LocalTime> | undefined, b: LocalTime | PlainMessage<LocalTime> | undefined): boolean {
    return proto3.util.equals(LocalTime, a, b);
  }
}

