// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file taptime/tz.proto (package com.whs31.taptime, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message com.whs31.taptime.Tz
 */
export class Tz extends Message<Tz> {
  /**
   * The IANA Time Zone identifier (e.g., "Europe/Berlin")
   *
   * @generated from field: string time_zone = 1;
   */
  timeZone = "";

  constructor(data?: PartialMessage<Tz>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.Tz";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "time_zone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Tz {
    return new Tz().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Tz {
    return new Tz().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Tz {
    return new Tz().fromJsonString(jsonString, options);
  }

  static equals(a: Tz | PlainMessage<Tz> | undefined, b: Tz | PlainMessage<Tz> | undefined): boolean {
    return proto3.util.equals(Tz, a, b);
  }
}

