// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file taptime/uid.proto (package com.whs31.taptime, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message com.whs31.taptime.Uid
 */
export class Uid extends Message<Uid> {
  /**
   * / RFID identifier
   * /
   * / Either 4, 7 or 10 bytes
   *
   * @generated from field: bytes value = 1;
   */
  value = new Uint8Array(0);

  constructor(data?: PartialMessage<Uid>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.Uid";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "value", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Uid {
    return new Uid().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Uid {
    return new Uid().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Uid {
    return new Uid().fromJsonString(jsonString, options);
  }

  static equals(a: Uid | PlainMessage<Uid> | undefined, b: Uid | PlainMessage<Uid> | undefined): boolean {
    return proto3.util.equals(Uid, a, b);
  }
}

