// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file taptime/user.proto (package com.whs31.taptime, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Duration, Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { Uuid } from "./uuid_pb.js";
import { Tz } from "./tz_pb.js";
import { Uid } from "./uid_pb.js";
import { Weekday } from "./weekday_pb.js";

/**
 * @generated from message com.whs31.taptime.User
 */
export class User extends Message<User> {
  /**
   * @generated from field: com.whs31.taptime.Uuid id = 1;
   */
  id?: Uuid;

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string email = 3;
   */
  email = "";

  /**
   * @generated from field: optional string organization = 4;
   */
  organization?: string;

  /**
   * @generated from field: com.whs31.taptime.Tz time_zone = 5;
   */
  timeZone?: Tz;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp last_seen = 7;
   */
  lastSeen?: Timestamp;

  /**
   * @generated from field: optional com.whs31.taptime.Uid rfid_uid = 8;
   */
  rfidUid?: Uid;

  /**
   * @generated from field: com.whs31.taptime.User.Settings settings = 9;
   */
  settings?: User_Settings;

  constructor(data?: PartialMessage<User>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.User";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: Uuid },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "organization", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "time_zone", kind: "message", T: Tz },
    { no: 6, name: "created_at", kind: "message", T: Timestamp },
    { no: 7, name: "last_seen", kind: "message", T: Timestamp, opt: true },
    { no: 8, name: "rfid_uid", kind: "message", T: Uid, opt: true },
    { no: 9, name: "settings", kind: "message", T: User_Settings },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): User {
    return new User().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): User {
    return new User().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): User {
    return new User().fromJsonString(jsonString, options);
  }

  static equals(a: User | PlainMessage<User> | undefined, b: User | PlainMessage<User> | undefined): boolean {
    return proto3.util.equals(User, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.User.Settings
 */
export class User_Settings extends Message<User_Settings> {
  /**
   * @generated from field: google.protobuf.Duration required_work_hours = 1;
   */
  requiredWorkHours?: Duration;

  /**
   * @generated from field: google.protobuf.Duration lunch_break_duration = 2;
   */
  lunchBreakDuration?: Duration;

  /**
   * @generated from field: repeated com.whs31.taptime.Weekday weekends = 3;
   */
  weekends: Weekday[] = [];

  /**
   * @generated from field: repeated com.whs31.taptime.Weekday remote_days = 4;
   */
  remoteDays: Weekday[] = [];

  constructor(data?: PartialMessage<User_Settings>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.User.Settings";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "required_work_hours", kind: "message", T: Duration },
    { no: 2, name: "lunch_break_duration", kind: "message", T: Duration },
    { no: 3, name: "weekends", kind: "enum", T: proto3.getEnumType(Weekday), repeated: true },
    { no: 4, name: "remote_days", kind: "enum", T: proto3.getEnumType(Weekday), repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): User_Settings {
    return new User_Settings().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): User_Settings {
    return new User_Settings().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): User_Settings {
    return new User_Settings().fromJsonString(jsonString, options);
  }

  static equals(a: User_Settings | PlainMessage<User_Settings> | undefined, b: User_Settings | PlainMessage<User_Settings> | undefined): boolean {
    return proto3.util.equals(User_Settings, a, b);
  }
}

/**
 * @generated from message com.whs31.taptime.User.Credentials
 */
export class User_Credentials extends Message<User_Credentials> {
  /**
   * @generated from field: com.whs31.taptime.Uuid id = 1;
   */
  id?: Uuid;

  /**
   * @generated from field: string email = 2;
   */
  email = "";

  /**
   * @generated from field: string password_hash = 3;
   */
  passwordHash = "";

  constructor(data?: PartialMessage<User_Credentials>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.User.Credentials";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: Uuid },
    { no: 2, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "password_hash", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): User_Credentials {
    return new User_Credentials().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): User_Credentials {
    return new User_Credentials().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): User_Credentials {
    return new User_Credentials().fromJsonString(jsonString, options);
  }

  static equals(a: User_Credentials | PlainMessage<User_Credentials> | undefined, b: User_Credentials | PlainMessage<User_Credentials> | undefined): boolean {
    return proto3.util.equals(User_Credentials, a, b);
  }
}

