// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file taptime/uuid.proto (package com.whs31.taptime, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message com.whs31.taptime.Uuid
 */
export class Uuid extends Message<Uuid> {
  /**
   * @generated from field: fixed64 most_significant_bits = 1;
   */
  mostSignificantBits = protoInt64.zero;

  /**
   * @generated from field: fixed64 least_significant_bits = 2;
   */
  leastSignificantBits = protoInt64.zero;

  constructor(data?: PartialMessage<Uuid>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.whs31.taptime.Uuid";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "most_significant_bits", kind: "scalar", T: 6 /* ScalarType.FIXED64 */ },
    { no: 2, name: "least_significant_bits", kind: "scalar", T: 6 /* ScalarType.FIXED64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Uuid {
    return new Uuid().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Uuid {
    return new Uuid().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Uuid {
    return new Uuid().fromJsonString(jsonString, options);
  }

  static equals(a: Uuid | PlainMessage<Uuid> | undefined, b: Uuid | PlainMessage<Uuid> | undefined): boolean {
    return proto3.util.equals(Uuid, a, b);
  }
}

