// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file taptime/weekday.proto (package com.whs31.taptime, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum com.whs31.taptime.Weekday
 */
export enum Weekday {
  /**
   * @generated from enum value: WEEKDAY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: WEEKDAY_MONDAY = 1;
   */
  MONDAY = 1,

  /**
   * @generated from enum value: WEEKDAY_TUESDAY = 2;
   */
  TUESDAY = 2,

  /**
   * @generated from enum value: WEEKDAY_WEDNESDAY = 3;
   */
  WEDNESDAY = 3,

  /**
   * @generated from enum value: WEEKDAY_THURSDAY = 4;
   */
  THURSDAY = 4,

  /**
   * @generated from enum value: WEEKDAY_FRIDAY = 5;
   */
  FRIDAY = 5,

  /**
   * @generated from enum value: WEEKDAY_SATURDAY = 6;
   */
  SATURDAY = 6,

  /**
   * @generated from enum value: WEEKDAY_SUNDAY = 7;
   */
  SUNDAY = 7,
}
// Retrieve enum metadata with: proto3.getEnumType(Weekday)
proto3.util.setEnumType(Weekday, "com.whs31.taptime.Weekday", [
  { no: 0, name: "WEEKDAY_UNSPECIFIED" },
  { no: 1, name: "WEEKDAY_MONDAY" },
  { no: 2, name: "WEEKDAY_TUESDAY" },
  { no: 3, name: "WEEKDAY_WEDNESDAY" },
  { no: 4, name: "WEEKDAY_THURSDAY" },
  { no: 5, name: "WEEKDAY_FRIDAY" },
  { no: 6, name: "WEEKDAY_SATURDAY" },
  { no: 7, name: "WEEKDAY_SUNDAY" },
]);

