// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BanRecord } from "./BanRecord";
import type { KnownIpAddress } from "./KnownIpAddress";
import type { User } from "./User";

export type AdminUserDetail = {
  user: User | null;
  knownIps: Array<KnownIpAddress>;
  bans: Array<BanRecord>;
  eventCount: number;
  dayFlagCount: number;
};
