// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Duration } from "./Duration";
import type { Empty } from "./Empty";

export type BalanceType = { "overtime": Duration } | { "exact": Empty } | {
  "underTime": Duration;
};
