// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BalanceType } from "./BalanceType";

export type Balance = { balanceType: BalanceType | null };
