// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timestamp } from "./Timestamp";
import type { Uuid } from "./Uuid";

export type BanRecord = {
  id: Uuid | null;
  kind: number;
  userId: Uuid | null;
  ipCidr: string;
  reason: string;
  createdAt: Timestamp | null;
  expiresAt: Timestamp | null;
  revokedAt: Timestamp | null;
  active: boolean;
};
