// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Uuid } from "./Uuid";

export type Credentials = {
  id: Uuid | null;
  email: string;
  passwordHash: string;
};
