// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Date } from "./Date";

export type DashboardRequest = {
  rangeStart: Date | null;
  rangeEnd: Date | null;
  monthStart: Date | null;
  monthEnd: Date | null;
  today: Date | null;
};
