// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DaySummary } from "./DaySummary";
import type { MonthlyStats } from "./MonthlyStats";

export type DashboardResponse = {
  days: Array<DaySummary>;
  monthStats: MonthlyStats | null;
};
