// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Date } from "./Date";
import type { Duration } from "./Duration";
import type { Event } from "./Event";

export type Day = {
  date: Date | null;
  events: Array<Event>;
  flags: number;
  requiredWorkHours: Duration | null;
  lunchBreakDuration: Duration | null;
};
