// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Balance } from "./Balance";
import type { Day } from "./Day";
import type { Duration } from "./Duration";

export type DaySummary = {
  day: Day | null;
  clockedWork: Duration | null;
  balance: Balance | null;
  skipped: boolean;
  fullDayWorked: boolean;
  requiredWorkHoursOverridden: boolean;
  workTarget: Duration | null;
};
