// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A generic empty message that you can re-use to avoid defining duplicated
 * empty messages in your APIs. A typical example is to use it as the request
 * or the response type of an API method. For instance:
 *
 * ```text
 * service Foo {
 *    rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);
 * }
 * ```
 */
export type Empty = Record<symbol, never>;
