// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Date } from "./Date";
import type { LocalTime } from "./LocalTime";

export type EventRequest = { date: Date | null; time: LocalTime | null };
