// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timestamp } from "./Timestamp";

export type KnownIpAddress = {
  ip: string;
  firstSeen: Timestamp | null;
  lastSeen: Timestamp | null;
  requestCount: number;
};
