// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BanRecord } from "./BanRecord";

export type ListBansResponse = { bans: Array<BanRecord> };
