// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminUserListItem } from "./AdminUserListItem";

export type ListUsersResponse = {
  users: Array<AdminUserListItem>;
  total: number;
};
