// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Duration } from "./Duration";

export type MonthlyStats = {
  totalClockedWork: Duration | null;
  overtime: Duration | null;
  undertime: Duration | null;
  workedDays: number;
  remoteDays: number;
  dayOffs: number;
  vacationDays: number;
  skippedDays: number;
  fullWeekendWorkDays: number;
  fullVacationWorkDays: number;
};
