// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from "./User";

export type RegisterUserRequest = {
  user: User | null;
  /**
   * / Plaintext password to be hashed and stored
   */
  password: string;
};
