// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Uuid } from "./Uuid";

export type RevokeBanRequest = { banId: Uuid | null; kind: number };
