// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Date } from "./Date";

export type SetFlagRequest = { date: Date | null; flag: number };
