// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Date } from "./Date";
import type { Duration } from "./Duration";

export type SetRequiredWorkHoursOverrideRequest = {
  date: Date | null;
  requiredWorkHours: Duration | null;
};
