// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Tz = {
  /**
   * The IANA Time Zone identifier (e.g., "Europe/Berlin")
   */
  timeZone: string;
};
