// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Uid = {
  /**
   * / RFID identifier
   * /
   * / Either 4, 7 or 10 bytes
   */
  value: Array<number>;
};
