// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Duration } from "./Duration";
import type { Tz } from "./Tz";

export type UpdateSettingsRequest = {
  timeZone: Tz | null;
  requiredWorkHours: Duration | null;
  lunchBreakDuration: Duration | null;
  weekends: Array<number>;
  remoteDays: Array<number>;
};
