// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Settings } from "./Settings";
import type { Timestamp } from "./Timestamp";
import type { Tz } from "./Tz";
import type { Uid } from "./Uid";
import type { Uuid } from "./Uuid";

export type User = {
  id: Uuid | null;
  name: string;
  email: string;
  organization: string | null;
  timeZone: Tz | null;
  createdAt: Timestamp | null;
  lastSeen: Timestamp | null;
  rfidUid: Uid | null;
  settings: Settings | null;
};
